### ISSUE TITLE
[akash] should probably use pruned snapshot by default? to save 8410% (400G => 4.7G) and speed up the deployment

### ISSUE THREAD

**Issue by arno01** [ovrclk/cosmos-omnibus#173]
Akash should probably use the pruned snapshot by default, to save 8410% (400G => 4.7G) as well as to speed up the deployment.

Change is simple =>

from:
```
  SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/akash/snapshot.json
```

to:
```
  SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/akash/pruned/snapshot.json
```

Ref.
- https://discord.com/channels/747885925232672829/751246770885099533/970252135637848074
- https://discord.com/channels/747885925232672829/751246770885099533/970322047110610944

**Comment by tombeynon** [comment]
This was done a few hours ago strangely!
