### ISSUE TITLE
update juno to v1.0.0

### ISSUE THREAD

**Issue by nullmames** [ovrclk/cosmos-omnibus#25]
mainnet

**Comment by tombeynon** [comment]
Juno v1.0.2 is in the latest release 🎉

**Comment by nullmames** [comment]
v1.0.0 is the current mainnet version. 
v2.0.0-alpha.3 is the current uni testnet version.

**Comment by tombeynon** [comment]
Downgraded in Omnibus v0.0.8, thanks dude 👌🏻
