### ISSUE TITLE
Error Warning when running ghcr.io/ovrclk/cosmos-omnibus:v0.2.8-cosmoshub-v7.0.2

### ISSUE THREAD

**Issue by kaisbaccour** [ovrclk/cosmos-omnibus#257]
ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.

**Comment by tombeynon** [comment]
This is standard node behaviour - you need to set a value for the minimum gas price. This can be done using an env var, e.g.`MINIMUM_GAS_PRICES=0.025uatom` or `GAIAD_MINIMUM_GAS_PRICES=0.025uatom`.

https://github.com/ovrclk/cosmos-omnibus#shortcuts
