### ISSUE TITLE
[question] AKASH_MODE env. variable

### ISSUE THREAD

**Issue by andy108369** [ovrclk/cosmos-omnibus#273]
Is `AKASH_MODE` somehow used or that's only to help the operator see what is the mode?

What would `AKASH_MODE=full` mean - that's not the `pruning=nothing` (i.e. archiving mode node).

Maybe we should remove `AKASH_MODE` or rename it (or update the readme) to reduce confusion?

```
cosmos-omnibus$ git grep AKASH_MODE
_examples/validator-and-private-sentries/deploy.yml:      - AKASH_MODE=validator
_examples/validator-and-private-sentries/deploy.yml:      - AKASH_MODE=full
_examples/validator-and-private-sentries/deploy.yml:      - AKASH_MODE=full
_examples/validator-and-public-sentries/sentries-deploy.yml:      - AKASH_MODE=full
_examples/validator-and-public-sentries/sentries-deploy.yml:      - AKASH_MODE=full
_examples/validator-and-public-sentries/validator-deploy.yml:      - AKASH_MODE=validator
```

**Comment by tombeynon** [comment]
This just sets the `mode` node config. `AKASH_` is just the prefix for the chain, could be GAIAD_MODE=full etc

**Comment by tombeynon** [comment]
Investigating further - `mode` seems to be an old config (previously accepted values like `full`, `validator` etc). I can't see in current config files, so I think we can remove this entirely.
