### ISSUE TITLE
Update Chain Registry codebase attributes

### ISSUE THREAD

**Issue by tombeynon** [ovrclk/cosmos-omnibus#289]
Chain Registry is moving a few key attributes into the `codebase` section - namely genesis_url, node_home and daemon_name, all of which are used in Omnibus.

https://github.com/cosmos/chain-registry/pull/738

**Comment by JeremyParish69** [comment]
I invite the maintainers to join the [Cosmos Chain Registry Working Group](https://t.me/+OkM0SDZ-M0liNDdh) at Telegram to keep up to date with any changes.
