### ISSUE TITLE
not working rest api on nodes

### ISSUE THREAD

**Issue by PR0F1L3R1** [ovrclk/cosmos-omnibus#301]
Hello, i'm trying to run evmos node with ghc.io/ovrclk/cosmos-omnibus:v0.3.5-evmos-v8.2.0. All working except 1317 port. In #85 @tombeynon replied 
> @kamsz The REST API is enabled using the tendermint config `api.enable`, so with environment variables for Chihuahua that would be `CHIHUAHUAD_API_ENABLE=true`. Then just expose `1317`.

I try to do with evmos node with environment variable `EVMOS_API_ENABLE=1` and `EVMOS_API_ENABLE=true`, but its not working. Then i try it with akash node with variable `AKASH_API_ENABLE=1` and its worked. How i can expose and enable 1317 port from docker?

**Comment by tombeynon** [comment]
Hi @PR0F1L3R1 - the namespace for Evmos is `EVMOSD` - it's typically the binary name in capitals. Some examples:

CosmosHub - gaid - GAID
Akash - akash - AKASH
Evmos - evmosd - EVMOSD
Chihuahua - chihuahuad - CHIHUAHUAD

So in your case: `EVMOSD_API_ENABLE=true` which I use all the time :)
