### ISSUE TITLE
Unable to pull ghcr.io/ovrclk/cosmos-omnibus:v0.3.15-osmosis-v13.0.0

### ISSUE THREAD

**Issue by kaladinlight** [ovrclk/cosmos-omnibus#370]
```
docker pull ghcr.io/ovrclk/cosmos-omnibus:v0.3.15-osmosis-v13.0.0
Error response from daemon: manifest unknown
```

Did the image push step get missed on this release?

**Comment by tombeynon** [comment]
Apologies I didn't realise that PR had been merged, I'll publish a new release now

**Comment by kaladinlight** [comment]
I did find: `ghcr.io/ovrclk/cosmos-omnibus:v0.3.16-rc1-osmosis-v13.0.0`

**Comment by tombeynon** [comment]
Awesome that's fine to use in the meantime, `ghcr.io/ovrclk/cosmos-omnibus:v0.3.16-osmosis-v13.0.0` is building now.

**Comment by kaladinlight** [comment]
> Awesome that's fine to use in the meantime, `ghcr.io/ovrclk/cosmos-omnibus:v0.3.16-osmosis-v13.0.0` is building now.

Sweet, thanks for the quick response!
