### ISSUE TITLE
quicksync: add -L to curl

### ISSUE THREAD

**Issue by ghost** [ovrclk/cosmos-omnibus#456]
`-L` should go here => https://github.com/akash-network/cosmos-omnibus/blob/v0.3.28/run.sh#L238

without `-L`:

```
$ curl -s https://quicksync.io/kava.json
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

with `-L`:

```
$ curl -Ls https://quicksync.io/kava.json
[
{"network": "pruned", "date": "2023-04-18 02:20:12", "link": .................
```

**Comment by fanbsb** [comment]
@tombeynon could you help look at this, QuickSync won't work with this issue

**Comment by tombeynon** [comment]
@fanbsb I'll get this sorted this week, in the meantime you can just follow the redirect in your browser and use the resulting URL as the `SNAPSHOT_QUICKSYNC` value:

```
- SNAPSHOT_QUICKSYNC=https://dl2.quicksync.io/json/kava.json
```
