### ISSUE TITLE
Setup API and swagger

### ISSUE THREAD

**Issue by Glacier-Luo** [ovrclk/cosmos-omnibus#85]
I want to run akash node on akash, but it seems that the image in this repo does not enable API and swagger, what should i do to enable them?

**Comment by tombeynon** [comment]
The RPC and REST APIs are enabled by default, you just need to expose the ports. RPC is `26657` and REST is `1317`. See [Tendermint docs for config](https://docs.tendermint.com/v0.35/tendermint-core/using-tendermint.html#configuration) and some [examples in this repo](https://github.com/ovrclk/cosmos-omnibus/tree/master/_examples/load-balanced-rpc-nodes).

I'm not sure about Swagger docs, this looks like Swagger for Tendermint at least https://docs.tendermint.com/master/rpc/

**Comment by kamsz** [comment]
@tombeynon Is this still true? After running Chihuahua image, REST seems to be disabled by default.

**Comment by tombeynon** [comment]
@kamsz The REST API is enabled using the tendermint config `api.enable`, so with environment variables for Chihuahua that would be `CHIHUAHUAD_API_ENABLE=true`. Then just expose `1317`.
