### ISSUE TITLE
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by btfdip** [ovrclk/cosmos-omnibus#96]
Hello, I tried to run full node locally myself. Could you help me out?

![image](https://user-images.githubusercontent.com/96004784/147414415-529d0357-7d89-4696-951f-486055408ae7.png)

**Comment by boz** [comment]
It looks like it may have not downloaded the correct genesis file for some reason.   Are you using [this](https://github.com/ovrclk/cosmos-omnibus/blob/e1e810ea899faa4cd72357d5e57a751e55732762/cosmoshub/docker-compose.yml#L12) `docker-compose.yml`?

**Comment by tombeynon** [comment]
Closing as this is definitely working now. @btfdip please try with the latest examples in the repo.
